requires 'IO::Socket';
requires 'MIME::Tools', '>= 5.509';
requires 'MIME::WordDecoder';
requires 'Digest::SHA';
requires 'Mail::SpamAssassin', '3.004006';
requires 'HTML::Parser';
requires 'Archive::Zip';
requires 'IO::Socket::SSL';
requires 'JSON';
requires 'LWP::UserAgent';
requires 'Mail::DKIM';
requires 'MIME-Tools', '>= 5.410';
requires 'Sys::Syslog';
requires 'ExtUtils::Embed';
requires 'Test::Most';
