name: mimedefang-postfix
services:
    mimedefang-postfix:
        container_name: mimedefang-postfix
        image: mimedefang/postfix:latest
        working_dir: /tests
        volumes:
         - .:/tests
        command: sh t/dockerPostfix.sh
