name: mimedefang-sendmail
services:
    mimedefang-sendmail:
        container_name: mimedefang-sendmail
        image: mimedefang/sendmail:v3.3
        working_dir: /tests
        volumes:
         - .:/tests
        command: sh t/dockerSendmail.sh
