services:
    mimedefang:
        container_name: mimedefang-postfix
        image: mimedefang/postfix:v3.3
        working_dir: /tests
        volumes:
         - .:/tests
        command: sh t/dockerPostfix.sh
