[supervisord]
nodaemon=true

[program:multiplexor]
startsecs = 0
autorestart = false
command=/bin/bash -c "/usr/bin/mimedefang-multiplexor -m 2 -x 10 -y 0 -U defang -b 600 -E -l -s /var/spool/MIMEDefang/mimedefang-multiplexor.sock"

[program:mimedefang]
startsecs = 0
autorestart = false
command=/bin/bash -c "/usr/bin/mimedefang -m /var/spool/MIMEDefang/mimedefang-multiplexor.sock -y -R -1 -U defang -r -H -s -t -q -p inet:10997"

[program:postfix]
startsecs = 0
autorestart = false
command=/bin/bash -c "/usr/sbin/postfix start"
