.\" $Id: watch-multiple-mimdefangs.8 9989 2004-09-22 14:08:58Z dfs $
.\""
.TH WATCH-MULTIPLE-MIMDEFANGS 8 "12 January 2007"
.UC 4
.SH NAME
watch-multiple-mimdefangs.tcl \- Keep an eye on a cluster of MIMEDefang machines
.SH SYNOPSIS
.B watch-multiple-mimdefangs.tcl [-n] [-r] [-s] [-t] [-archive] \fR\fImachine-1 machine-2 ... machine-N\fR

.SH DESCRIPTION

\fBwatch-multiple-mimdefangs.tcl\fR is a Tk script that graphically
displays the status of \fBmimedefang-multiplexor\fR(8) on a cluster of
machines.  Note that Tcl/Tk 8.4 or higher is required to run
\fBwatch-multiple-mimdefangs.tcl\fR.

If you supply the \fB-archive\fR command-line option, then
\fBwatch-multiple-mimdefangs.tcl\fR logs the output of
\fBmd-mx-ctrl rawload\fR for each machine.  The output for \fImachine_name\fR is logged in:

$HOME/.watch-multiple-mimedefangs/\fImachine_name\fR/data.

If you supply any of \fB-n\fR, \fB-r\fR, \fB-s\fR or \fB-t\fR
options, then \fBwatch-multiple-mimdefangs.tcl\fR uses the
\fBrawload1\fR command rather than \fBrawload\fR command to read
performance data.  \fIDo not use these options unless all monitored
machines are running MIMEDefang 2.74 or newer!\fR.

The \fB-n\fR, \fB-r\fR, \fB-s\fR, and \fB-t\fR options enable
monitoring of scan times, filter_relay times, filter_sender times
and filter_recipient times, respectively.

.SH PREREQUISITES

To use \fBwatch-multiple-mimdefangs.tcl\fR to monitor a cluster of machines,
you need the following prerequisites:

.TP
.B o
A UNIX-like machine with Tcl/Tk 8.4, the X window system and an SSH client.
You also need "xterm" to use some of the features.

.TP
.B o
The ability to SSH \fIas root\fR to all of the machines you want to monitor.
Ideally, you should be using the SSH agent so that you can SSH to the
monitored machines as root without being prompted for a password or
pass phrase.

.TP
.B o
The program \fBmd-mx-ctrl\fR on root's path on all the machines you want
to monitor.

.SH DISPLAY

For each machine specified on the command line, \fBwatch-multiple-mimdefangs.tcl\fR creates a chart with five columns.  The columns are:

.TP
.B o
A button with the name of the machine.  Clicking the button pops up
a menu that lets you take various actions, as described later.  If all workers
on the machine are busy, the button turns yellow.

.TP
.B o
A label showing the number of busy workers in the form "busy/total", where
total is the total number of workers.

.TP
.B o
A label showing the average number of messages per second over the last
10 seconds.

.TP
.B o
A label showing the average number of milliseconds per scan over the
last 10 seconds.

.TP
.B o
A chart that graphs the average number of busy workers, the average
number of messages per second and the average scan time in milliseconds,
all averaged over the last 10 seconds.

.SH MACHINE MENU

If you click on a machine name, a menu with three options pops up:

.TP
.B SSH
Open an xterm session and ssh as root to the machine.

.TP
.B Busy Workers
Monitor the busy workers on the machine.  If you click on the
process-ID of a worker, an xterm will open up and the command "strace
-s 100 -t -p \fIpid\fR" will be executed on the remote machine.  This
is Linux-specific, but you can edit
\fBwatch-multiple-mimdefangs.tcl\fR to replace the command with your
particular system's command for tracing system calls.

.TP
.B Delete
Remove the machine from the list of machines being monitored.

.SH ADDING A MACHINE

If you need to add a machine to the display, simply type the name of the
machine in the "Add Machine:" box and press Enter.

.SH AUTHOR
\fBwatch-multiple-mimdefangs.tcl\fR was written by Dianne Skoll.

.SH SEE ALSO
mimedefang.pl(8), mimedefang-filter(5), mimedefang(8), mimedefang-protocol(7),
md-mx-ctrl(8), watch-mimedefang(8)


